- name: Copy {{ redis_1_host }} config file
  template:
    src: "templates/{{ redis_1_host }}_config.j2"
    dest: "/data/{{ redis_1_host }}_config.conf"
    force: yes
    mode: 0755

- name: Start "{{ redis_1_host }}"
  docker_container:
    command: redis-server /etc/redis/redis.conf
    name: "{{ redis_1_host }}"
    hostname: "{{ redis_1_host }}"
    image: redis:6
    state: started
    restart_policy: always
    expose: "{{ redis_1_port }}"
    ports: "{{ redis_1_port }}:{{ redis_1_port }}"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - /data/{{ redis_1_host }}:/data
      - /data/{{ redis_1_host }}_config.conf:/etc/redis/redis.conf
  register: redis_1_container

- name: Copy {{ redis_2_host }} config file
  template:
    src: "templates/{{ redis_2_host }}_config.j2"
    dest: "/data/{{ redis_2_host }}_config.conf"
    force: yes
    mode: 0755

- name: Start "{{ redis_2_host }}"
  docker_container:
    command: redis-server /etc/redis/redis.conf
    name: "{{ redis_2_host }}"
    hostname: "{{ redis_2_host }}"
    image: redis:6
    state: started
    restart_policy: always
    expose: "{{ redis_2_port }}"
    ports: "{{ redis_2_port }}:{{ redis_2_port }}"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - /data/{{ redis_2_host }}:/data
      - /data/{{ redis_2_host }}_config.conf:/etc/redis/redis.conf
  register: redis_2_container


- name: Copy {{ redis_3_host }} config file
  template:
    src: "templates/{{ redis_3_host }}_config.j2"
    dest: "/data/{{ redis_3_host }}_config.conf"
    force: yes
    mode: 0755

- name: Start "{{ redis_3_host }}"
  docker_container:
    command: redis-server /etc/redis/redis.conf
    name: "{{ redis_3_host }}"
    hostname: "{{ redis_3_host }}"
    image: redis:6
    state: started
    restart_policy: always
    expose: "{{ redis_3_port }}"
    ports: "{{ redis_3_port }}:{{ redis_3_port }}"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - /data/{{ redis_3_host }}:/data
      - /data/{{ redis_3_host }}_config.conf:/etc/redis/redis.conf
  register: redis_3_container

- name: Execute redis-cli inside docker container
  command: >
    docker exec -i {{ redis_1_host }} bash -c
    "redis-cli --cluster create
    {{ redis_1_container.ansible_facts.docker_container.NetworkSettings.IPAddress }}:7000
    {{ redis_2_container.ansible_facts.docker_container.NetworkSettings.IPAddress }}:7001
    {{ redis_3_container.ansible_facts.docker_container.NetworkSettings.IPAddress }}:7002
    --cluster-yes"