- name: Install Redis Module for Python
  pip:
    name: redis

- name: "Copy config file"
  template:
    src: "templates/redis_config.j2"
    dest: "/data/redis_{{ item }}.conf"
    force: yes
    mode: 0755
  with_sequence: count={{ redis_nodes }}

- name: "Start redis_host"
  docker_container:
    command: redis-server /etc/redis/redis.conf
    name: "{{ redis_host_prefix }}{{ item }}"
    hostname: "{{ redis_host_prefix }}{{ item }}"
    image: redis:6
    state: started
    restart_policy: always
    expose: "{{ redis_port_prefix }}{{ item }}"
    ports: "{{ redis_port_prefix }}{{ item }}:{{ redis_port_prefix }}{{ item }}"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - /data/redis_{{ item }}:/data
      - /data/redis_{{ item }}.conf:/etc/redis/redis.conf
  register: containers_info
  with_sequence: count={{ redis_nodes }}

- name: Initialize connection_string variable
  set_fact:
    connection_string: ""

# Install jmespath python module, required by json_query, https://github.com/ansible/ansible/issues/69148
- name: Install python3-jmespath
  apt:
    name: python3-jmespath
    state: present
    update_cache: yes

- name: "Create cluster connection string"
  with_items: "{{ containers_info.results }}"
  loop_control:
    label: "{{ item.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
  set_fact:
    connection_string: "{{ connection_string }}
      {{ item.ansible_facts.docker_container.NetworkSettings.IPAddress }}:{{ item.ansible_facts.docker_container.HostConfig.PortBindings|json_query('*[].HostPort') | first }}"
- debug:
    msg: "{{ connection_string }}"

- name: Execute redis-cli inside docker container
  command: >
    docker exec -i {{redis_host_prefix}}1 bash -c
    "redis-cli --cluster create {{ connection_string }} --cluster-yes"