---
mysql_backups_dir: /var/mysql/backups
mysql_character_set: utf8mb4
mysql_collation: utf8mb4_unicode_520_ci
mysql_conf_dir: /etc/mysql/conf.d
mysql_config_mysqld:
  max_connections: 500
  skip_name_resolve: "true"
mysql_container_name: mysql
mysql_env: {}
mysql_network: mysql
mysql_state: started
mysql_root_user: root

mysql:
  master:
    container_name: mysql_master
    port: 3306
    lib_dir: /var/mysql/master/lib
    backups_dir: /var/mysql/master/backups
  slave:
    container_name: mysql_slave
    port: 3307
    lib_dir: /var/mysql/slave/lib
    backups_dir: /var/mysql/slave/backups
  replication:
    username: replication
    password: Aepeena6Thi3ohzo
