---
- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  vars:
    python_version: python3.7
    pip: python3-pip
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: 'iu4cheeCiet7oeRa'
    docker_network: testtask
    rabbitmq_user: admin
    rabbitmq_password: 'iu4cheeCiet7oeRa'
    redis_nodes: 3

  roles:
    - role: python
    - role: docker
    - role: rabbitmq
    - role: redis
    - role: mysql