---
- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  vars:
    python_version: python3.7
    pip: python3-pip
    pip_modules: docker
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: 'iu4cheeCiet7oeRa'

  roles:
    - role: python
    - role: docker
    - role: redis
    - role: rabbitmq
    - role: mysql