- name: Start rabbitmq primary node
  docker_container:
    env:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
    name: rabbitmq-primary
    hostname: rabbitmq-primary
    image: lucifer8591/rabbitmq-server:3.7.17
    state: started
    restart_policy: always
    exposed_ports:
      - "5672"
      - "15672"
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      - name: "{{ docker_network }}"

- name: Start rabbitmq secondary node
  docker_container:
    env:
      CLUSTERED: "true"
      CLUSTER_WITH: "rabbitmq-primary"
      RAM_NODE: "true"
    name: rabbitmq-secondary
    hostname: rabbitmq-secondary
    image: lucifer8591/rabbitmq-server:3.7.17
    links:
      - rabbitmq-primary
    state: started
    restart_policy: always
    ports:
     - "5673:5672"
     - "15673:15672"
    networks:
      - name: "{{ docker_network }}"