- name: Install {{ python_version }}
  apt:
    name: "{{ python_version }}"
    state: present
    update_cache: yes
  when: python_version is defined
- name: Install {{ pip }}
  apt:
    name: "{{ pip }}"
    state: present
    update_cache: yes
  when: pip is defined