- name: Install {{ python_version }}
  apt:
    name: "{{ python_version }}"
    state: present
    update_cache: yes
  when: python_version is defined
- name: Install {{ pip }}
  apt:
    name: "{{ pip }}"
    state: present
    update_cache: yes
  when: pip is defined

# Install jmespath python module, required by json_query, https://github.com/ansible/ansible/issues/69148
- name: Install python-jmespath
  apt:
    name: python-jmespath
    state: present
    update_cache: yes