---
#tasks file for containers
- include: images.yml
- include: network.yml
- include: mysql-conf.yml
- include: container.yml
- include: set-replication.yml
  when: mysql_servers|int > 1
- include: user.yml
